customize redirect url after masquerade
foundertherapy/django-users-plus pull request #30
Opened 2017-07-20 11:14 UTC by GhalebKhaled

2017-07-20 11:16 UTC, GhalebKhaled commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Admin - Enhancement in 'Sign In' in users table [Cycle27]](https://trello.com/c/0MhlmdI8/1556-1-admin-enhancement-in-sign-in-in-users-table-cycle27)

2017-07-20 13:21 UTC, awartani approved these changes

2017-07-31 14:09 UTC, GhalebKhaled commented
![](https://github.trello.services/images/mini-trello-icon.png) [DS - Django - Enhancement in 'Sign In' in users table](https://trello.com/c/vCtqh35g/82-ds-django-enhancement-in-sign-in-in-users-table)

2017-07-31 15:12 UTC, alaayameen requested changes

2017-07-31 15:12 UTC, alaayameen commented on accountsplus/settings.py
> +MASQUERADE_REDIRECT_URL = get_setting('MASQUERADE_REDIRECT_URL', False)
@GhalebKhaled no need for this.

2017-07-31 15:12 UTC, alaayameen commented on accountsplus/views.py
> +        return django.http.HttpResponseRedirect(settings.MASQUERADE_REDIRECT_URL)
@GhalebKhaled Please use the default login url

2017-08-01 14:46 UTC, awartani approved these changes

2017-08-13 15:15 UTC, awartani approved these changes

2017-08-13 16:11 UTC, merged